### ISSUE TITLE
ECMAScript room

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#10]
If anyone has any issues or questions related to the ES room please discuss

**Comment by Jhawins** [comment]
Nothing to discuss. Conversation had a beginning, middle and an end.

**Comment by Jhawins** [comment]
> Public Service Announcement: Looks like more people are coming to the ES room. It's Not JavaScript Room #2. It does not replace it - it does not supplement it - the rooms do not share goals at all. The ES room does not have any longevity goals and if discussion exhausts itself it can die tomorrow and all will be cool with it. If you have relevant experience feel free to ask for access.

> To which Jhawins replied:

> I'll see through your bullshit on Saturday just as well as on Friday, @BenjaminGruenbaum.

^ This isn't the order in which things happened and my messages were not direct replies. You can't just grab pieces of a conversation and put them together back to back.

**Comment by ndugger** [comment]
I wholeheartedly believe that the ES room is a great idea; I absolutely appreciate a place to discuss high level things without newbies asking about jquery plugins and the like.

However, It's awfully silly to deny that you didn't want room number 8 to seem more superior to the JS room. If you really didn't care about looking better than the JS room, you would have simply created another chat room instead of getting a moderator involved.

That being said, I still support the existence of that room, but please, everyone just needs to be honest with each other here.

**Comment by loktar00** [comment]
Yeah while I don't think its out of the realm to discuss the topic of the ES room, I disagree with the way it has been brought up.

I think something along the lines of

> If anyone has any issues or questions related to the ES room please discuss

would be more appropriate.

**Comment by benjamingr** [comment]
@loktar00 I'm for that, care to make the edit?

**Comment by ssube** [comment]
Speaking as somebody who has not been invited (or applied) to the New Secret Room, I do think there's some sense in having a room about discussing the spec vs using the language and libraries.

While they are closely related, language-lawyer discussions tend to be long and super technical, making them confusing (at best) in the normal room and to some of the more casual users. Exposing them to the spec is probably a good thing, but it is hard to get into the details between pictures of cannibals.

**Comment by loktar00** [comment]
@benjamingr edited.. that's what you meant right? heh feels weird putting words into your mouth so to speak :p

**Comment by benjamingr** [comment]
@loktar00 thanks. That's exactly what I meant.

**Comment by rlemon** [comment]
I'm for the room, I'm not for locking it down. I've made this argument a few times in the chat. If anyone would like I'll paste those links in here.

**Comment by benjamingr** [comment]
@ssube you're welcome to that room of course, we've literally accepted every application to that room by existing JS ROs except for @Jhawins who's welcome to apply again and wasn't added only because of the initial drama.

**Comment by MadaraUchiha** [comment]
Just a clarification. The room number is completely and absolutely
arbitrary. I looked over the room numbers in order and commandeered the
first one that was unused for years. The only intention was to shorten the
URL, not to make anyone feel less or more superior. (Had I wanted to, I
would have picked 16).

**Comment by rlemon** [comment]
@MadaraUchiha it just seems very odd. I've never seen a room recycled before. I'm not sure if the system or you reset the created date.. seemed shifty overall.

**Comment by Retsam** [comment]
I'm in the same camp as @rlemon: I like the room idea, I don't think it should be locked down.  I've got my reasoning for that [in gist form](https://gist.github.com/Retsam/2cc204fc60fc77f5aabc).

**Comment by Canop** [comment]
How do you apply to that room ? the ES room I know has been frozen since ages

**Comment by ndugger** [comment]
@Canop with this new one, you have to ping Benji, and go through a silly interview process before he'll give you access.

**Comment by Canop** [comment]
@benjamingr ping! ( yes, I know what a promise is, it's that thing you have in jquery to make synch requests, right ? )

**Comment by benjamingr** [comment]
Click "request access" - it'll be approved.

**Comment by awalGarg** [comment]
I denied write access to @ndugger and @Jhawins that day from the ES room. Twice both. Here is some clarification to that, and answer to some questions that followed.

First of all, I'd like to apologize, I should have communicated better with both. It was not my intention to create a conflict or an argument. In the future I'll try to communicate things better in real time.

The ES room is about high level discussion of the ECMAScript specification. Having an understanding of ECMAScript at a userland level is very different from having an understanding of the ECMAScript specification. Having interacted with both users, I was not aware that either user had _interest_ in the specification or have met any of the qualifications in the room guidelines so I denied their applications and made a mental note to discuss it with other room owners.

In a sentence, what happened is that I did not want to authorize their access without first discussing it with other room members. I made the fact I denied them both access public - I did not mean to "brag" about it or somehow appear to be "their superior", I apologize if that's the impression I created. To be fair, it's not like either of them were exactly "strictly professional" about the ordeal - calling me names and fueling the drama.

I'd like to see how we can move forward and not bicker about the past. I'll do my best to communicate better.

**Comment by ndugger** [comment]
See, that's just bogus--You somehow feel that leaving a comment on an ES Discuss thread has made you more qualified to discuss the language spec than those of us who have explored and researched the spec without having participated in discussion on that specific avenue. 

In Benjamin's rules for the room, it was made clear that ES Discuss participation was only one way in which you could qualify for participation the chat room, yet you refused to take anything into consideration that was otherwise not aligned with your own experience.

Your attitude was particular toxic in this case; it should have been handled much better than it was.

However, I don't say this to point fingers at you specifically, but at the culture of users in the ES room. As I said earlier, I think the room is a good idea, but the general personality in there is far more negative towards users than anything in the JS room.

**Comment by Jhawins** [comment]
Just FYI, @Madara, I had for some reason thought JS was #7, and that you
chose #8 so as to be its successor. Not I realize the original is #17 and
this is bogus haha. My bad for the weirdness over the number.

**Comment by Zirak** [comment]
@ndugger 
> However, It's awfully silly to deny that you didn't want room number 8 to seem more superior to the JS room.

That's not the reason a low number was picked. A low number room was commandeered because room 2763 looks ugly. This has nothing to do with elitism.

> In Benjamin's rules for the room, it was made clear that ES Discuss participation was only one way in which you could qualify for participation the chat room [...]

That's not the only way. I never posted to es-discuss, nor did @ralt (I think?), nor did @Canop. We're all just js room regulars.

> [...] the general personality in there is far more negative towards users than anything in the JS room.

How can you point to a general personality? The room's been alive for a week, and it seems to be working so far. We've had pretty healthy discussions there. Where does the supposed elitism emanate from?

This has been repeated endlessly, and I've silently agreed until now, but in all honesty I'm very glad that this is a thing now. I love helping people learn and explore javascript, but where can I go to grow as a developer? The only times I've had decent arguments in the js room *about js things which I didn't know* was with the same small number of people, who are now all in the ES room.

Not being inclusive by default is the point. Having high level discussions is the point. Learning what closures are is never discouraged, it just won't happen there.

Sounds okay?

**Comment by ndugger** [comment]
I said that ES Discuss participation was only **one** way, not the only way. I'm also a JS room regular, and was denied multiple times by Awal, so that's just nonsense.

**Comment by MadaraUchiha** [comment]
Meh, commandeering the room number was a mistake. In hindsight I probably
should not have done it.

**Comment by rlemon** [comment]
@MadaraUchiha it could set the precedence for doing this going forward. **It does** stamp the room as a room which now has "Moderator Approval" which may cause some people to be uneasy. But aside from that recycling rooms isn't really an issue, just odd because this is the first time (afaik) that it has happened on chat.so

**Comment by benjamingr** [comment]
@ndugger what exactly do you think "specifically pointing fingers at Awal" will accomplish? He already apologized for his behavior and explained it. 

He wasn't acting maliciously or anything and it sounds like a big mixup more than anything else.

**Comment by ndugger** [comment]
He was acting maliciously; you being blind to the issue doesn't mean that it didn't happen.

**Comment by Jhawins** [comment]
He kinda has a point....

Thanks,
Josiah South

**Comment by maniator** [comment]
@benjamingr Can I get in on the new room? I am very interested in any new discussion on the project :-)

**Comment by benjamingr** [comment]
You can request access. In all likelihood it would be approved.

**Comment by maniator** [comment]
Thanks @benjamingr  :+1:
