### ISSUE TITLE
Star policy

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#22]
Should we enforce a policy on what messages get starred? Should context be relevant?

Do we unstar NSFW? 

Do we unstar messages containing words like "fuck" and "shit"? 

Do we only want _professional messages_ (relating to JS etc) to be starred?

**Comment by AmaanC** [comment]
I think we should leave the stars list as it is right now. If any messages
_are_ problematic, they'll probably be flagged and be dealt with anyway.

**Comment by rlemon** [comment]
:+1: Amaan

**Comment by luggage66** [comment]
My opinion:
- MUST unpin NSFW and Spam.
- MAY unpin profanity without context or something you consider flag-bait.

I don't think we should/need to try to enforce on-topic or 'quality' beyond that.

**Comment by benjamingr** [comment]
Luggage: unpin or unstarred?

**Comment by benjamingr** [comment]
One day I'm going to find the person responsible for the fact I can't edit in GH's mobile UI and spit in their beer 😡

**Comment by luggage66** [comment]
Ohh, I don't know. I was thinking to unpin from the sidebar for general room atmosphere. I'm not sure I care as much about the stars.

**Comment by loktar00** [comment]
Not a fan of NSFW content being pinned really, as for stars as long as they are tagged NSFW, since they don't stay long anyway it doesn't seem like a huge deal. However NSFW content is rarely starred.

Stars are pretty organic in nature, to enforce a staring policy seems a bit over the top. We have used pretty good judgement thus far I think.

We have never had an "issue" with profanity that I can really recall, and I would find it highly hypocritical remove stars against anything with a swear word due to the fact @Zirak XHR story was pinned for so long.

**Comment by Zirak** [comment]
NSFW rules are pretty obvious; they don't belong in pins in general, they don't belong in the room unless tagged.

As for profanity, @loktar00's right. The room at large doesn't care about profanity.

While on-topicness isn't mandatory, and it's nice to see amusing stars once in a while, I have several times un_starred_ messages which were only relevant for the person or persons in that point in time (yes, even when I was starred).
For instance, someone answered someone else in some inane topic, it got starred for some reason. Or useless messages. I think we can count on semi-healthy judgement in these cases.

**Comment by monners** [comment]
I agree with Amaan and Zirak.  Common sense.

**Comment by Cerbrus** [comment]
Common sense is the way to go.

Why should messages that are "ok" in the room itself, not be allowed to be starred?  
If a message violates some rules, it usually gets removed quick enough, any way.

**Comment by RUJodan** [comment]
NSFW material should not be pinned.

Profanity has been around forever, and it's never generated an issue with mods. Leave it. If it's offensive or flaming, it will be handled.

**Comment by FirstWhack** [comment]
Everyone is discussing pins and stars as equals, they are not equals. 

We could have stricter policies for what can be _pinned_ because those things are by ROs and could be considered more "official" in some way (out of scope for this issue).

As for stars we do a pretty good job of removing things when necessary, don't think any changes are necessary. 
Unless there is an example or reason for something to be changed we should just leave it alone. If stars are ever a problem let's address it at that time.

**Comment by FirstWhack** [comment]
Pinned messages discussion at #23

**Comment by FirstWhack** [comment]
Closing this as well as #23

Use common sense when starring, ROs remove inappropriate stars when they happen.
