### ISSUE TITLE
Repercussions for breaking the process

### ISSUE THREAD

**Issue by FirstWhack** [JavaScriptRoom/culture#27]
Recently a user was added without prior discussion or announcement. How do we handle existing ROs stepping outside of the process?

**Comment by kendfrey** [comment]
If it causes a problem, talk about it. I don't think it's a problem in itself, and "repercussions" is probably a little over the top.

**Comment by FirstWhack** [comment]
My opinion is to immediately remove the new owner as well as the offending RO.
Then create an issue about the offending RO who will be either voted back in or sent on their way after 72 hours, THEN the new RO can be voted on. 

So basically suspend the offending RO and throw out the unannounced addition.

**Comment by FirstWhack** [comment]
@kendfrey I am going to go out on a limb and say any time someone doesn't follow the process we have out in place it automatically "causes a problem".

**Comment by FirstWhack** [comment]
Let's either have a system where we track these types of additions and issues or lets not have it. All or nothing, we all need to play by the rules or get rid of them.

**Comment by benjamingr** [comment]
Link to what happened?

**Comment by FirstWhack** [comment]
BadgerCat added SomeKittens without so much as mentioning it on the GH. 
There is already an issue for that and the specific case is irrelevant.

When someone breaks the process, i.e. goes rogue and adds an owner without consulting the GH, what do we do? I am suggesting we remove both and create an issue to discuss each case on GH, re-add one or both of them -or not- depending on the outcome of that issue.

**Comment by benjamingr** [comment]
That happened before we had decided to raise everything on GH and make choices here IIRC. Can you check the dates?

**Comment by FirstWhack** [comment]
@benjamingr oh! Great, there isn't an impending issue right now then.

So when it happens in the future, what do we do?

**Comment by benjamingr** [comment]
Remove both, open issues for each on GH, probably

**Comment by ssube** [comment]
I think removing the "offending" RO as well is a little drastic, especially
if they have an otherwise good record. That goes double with GH being a
fairly new addition to how we handle problems.

In this case, it's entirely possible BadgerCat missed the convo leading to
SomeKittens being removed and was just fixing the list (since joke removals
used to be a thing, that's not much of a stretch).

**Comment by benjamingr** [comment]
See the debate above, I'm not suggesting we remove badgergirl @ssube

**Comment by Zirak** [comment]
If this was a gravely important process, like a nuclear launch facility, then I would've agreed with you.

But it's a room of people talking about javascript and such. We should be chill about these things. :)

An RO broke the rules or the procedure? Fine, that happens. Talk to the offending RO. Thinking they've "gone rogue" is believing the worst in your fellow ROs.

**Comment by loktar00** [comment]
Meh yeah I agree with @Zirak. If an RO adds someone else as an RO and we didn't discuss it the best course of action is just to remove that new RO and have a discussion.

If it became a trend though it would be a good idea to discuss it further.

**Comment by AmaanC** [comment]
:+1: for removing the new RO and discussing things

**Comment by Trasiva** [comment]
:+1: ROs should be a majority vote and not whimsically added by people.  The case with Badgercat was likely an oversight due to missing the situation as @ssube mentioned.

I vote for removing the new RO, creating an issue here on GH regarding if they should be an RO, and a discussion with the RO that did the promotion. There's no reason to just up and remove an existing RO giving them a chance to explain why they did what they did, especially if it's just an oversight or they weren't aware of a previous conversation.

**Comment by Zirak** [comment]
Closing due to public disinterest.
