### ISSUE TITLE
Keeping RO discussions in the public repo

### ISSUE THREAD

**Issue by ssube** [JavaScriptRoom/culture#32]
I see being an RO as a very limited sort of public servant, so I think we should keep all discussions related to electing, impeaching, and debates between ROs in the public repo. 

It's important that both existing ROs and other users be able to support or voice concerns about an RO, especially when we're discussing adding or removing someone.

This is not about trolls in general (I agree with @MadaraUchiha there, the potential for abuse is a problem), just votes and group discussions related to RO status.

Thoughts?

**Comment by AmaanC** [comment]
Sounds fair to me.

**Comment by benjamingr** [comment]
:+1:

**Comment by Trasiva** [comment]
I think that's exactly how it should be. ROs are responsible for the QOL within the chat, and therefore transparency is a must.

**Comment by ssube** [comment]
Also, this is largely a duplicate of #29, but I hope we can codify how that applies to RO status.

**Comment by loktar00** [comment]
:+1: \*  :100: 
 (just wanted to use the 100 icon)

**Comment by Zirak** [comment]
I originally made that issue in a private room because the implications of it being in the open worried me a bit. Let's say that you the were the subject of the discussion of keeping you an RO, it spanned several personal topics and at the end you stay an RO then that discussion would potentially be a blemish on your name.

That felt like something I wouldn't have wanted to be done to me so I opened it in a private room to be hashed out, but the final decision should be of course done in a public repo.

**Comment by Canop** [comment]
This is a valid point. We should be able to say that we don't think X is able to be a RO without risking embarrassing him elsewhere (job, friends, presidential race, etc.)

**Comment by MadaraUchiha** [comment]
+1.

**Comment by loktar00** [comment]
Closing, consensus sounds like we discuss any RO actions, happenings in the public eye.
