### ISSUE TITLE
Make the Room a Gallery

### ISSUE THREAD

**Issue by benjamingr** [JavaScriptRoom/culture#61]
In lieu of the recent atmosphere where we're being attacked by toxic people from twitter who wish to delegitimise our culture. I figure we should find a way to explicitly be _less_ inclusive and welcoming in order to stop being attacked and eventually burn out.
 
To give context to users who are not up with the current state of events, here is where things went down:

 - [Chat transcript](https://chat.stackoverflow.com/transcript/message/42306421#42306421)
 - [StackOverflow Meta](https://meta.stackoverflow.com/questions/366793/recourse-for-inappropriate-so-chat-conversation/366802#366802)
- [Twitter](https://twitter.com/JayHanlon/status/990359557384876033)

From that place, we would also like to ask you to *not* go and instigate any more drama there, especially on Twitter.

 We also want to minimize the amount of crap StackOverflow has to deal with - I recommend that we:

 - Rename the chat room to ECMAScript.
 - [Move the room to gallery](https://stackoverflow.com/help/privileges/gallery-chat-rooms), making it explicitly exclusive to users who have not confirmed they've read the rules and know how to conduct themselves.
 - Revisit both those in a month, and lift these restrictions when things calm down.

We don't have a policy for deciding on either of those things - so I'm going to go on the safe side and go with a 72 hour majority vote.

 - 👍 - rename the room and make it gallery until June 3rd where a second vote will take place.  
 - 👎-  don't rename the room nor make it a gallery
 - ❤️ - technically 2.9 is <3, which is an easily ignored fact we've known for years.

**Comment by benjamingr** [comment]
The other plus side is that this way Oracle can't sue us for using JavaScript which they have a trademark for.

**Comment by Cerbrus** [comment]
👍🏻 (Replying from my phone)

I don’t like building a wall like this, but if we must, we must.

**Comment by darkyen** [comment]
As a less scary alternative, how about moving _our_ conversations to Miaou for a while?

**Comment by benjamingr** [comment]
@darkyen we did that once before, it wasn't great IMO - I still want to _actually_ be inclusive towards people who come to the room in good faith and want to participate.

Namely, I'd even like to find ways to encourage more actual diversity in the room eventually while only driving away people who come in bad faith in an effort to carve a piece of internet drama at our expense.

**Comment by surajrao** [comment]
Agreed. I don't believe censorship is actually going to make a place inclusive at all though.

**Comment by benjamingr** [comment]
> Agreed. I don't believe censorship is actually going to make a place inclusive at all though.

I'm open to ideas that would allow us to take in reasonable people who come in good faith while keeping abusers outside.

**Comment by joshleblanc** [comment]
I don't like the idea of switching to gallery. I feel like it's just another thing for people to latch on to and complain about.

I propose we change the name of the channel to "rlemon party & 3D printing general discussion".

That should clear up any misunderstandings about the purpose of the room.

**Comment by oliversalzburg** [comment]
If this is mostly fueled by the events noted in https://github.com/JavaScriptRoom/moderation/issues/67, then this is an overreaction. It's too soon and too harsh.

I don't really see a problem right now. I enjoy the fresh people coming in and asking their "stupid questions". You give them a salty reply and they are either driven away or develop into a fun new member of the room (or anything in between). I also enjoy the people who get pissed off because of whatever we're discussing at the moment and they are not used to the nonsense that is often interleaved with serious arguments. 

It's a lot of fun talking with the regulars, but the newbies are the spice in the soup. It brings a certain dynamic to the room. Certain aspects of how we communicate and have fun with each other depend on people who are not "in the loop" IMHO.

And trolls will be trolls. If we're reacting like *this* because of someone bitch-whining on Twitter, then we are no better than them. And being better than others is really important.

I don't think I have to hide my personality behind closed curtains or that I can only speak my mind in a closed circle of my peers. I will continue to loudly express any stupid idea I have in my mind until someone steps in and tells me "No, no, bad Oliver. You are now banned from SO for life because you said 'poop' too many times." I don't have to take myself off the stage proactively and neither do any of you.

So, that's a :-1: from me.

**Comment by towc** [comment]
I'd like to vote only for renaming the room.

The idea of the gallery is nice, but only if new people can join. Maybe we can have a website, for example the current http://javascriptroom.com, where the users have to tick a box (and maybe take a minor quiz, so it's not just a thing to shrug at), and then cap will add them to the room automatically?

**Comment by joshleblanc** [comment]
I don't like the idea of the gallery due to the sheer number of people who get referred to the chat because their questions don't belong in main. 

We get a *lot* of questions throughout the day. I'd like to say a lot of them go answered, too, even if some get ignored. 

Some of the people who show up to ask a question even stick around, which is always good for the community.

**Comment by MadaraUchiha** [comment]
I disagree with making the room a gallery, so much so as to go as far and putting on my "I'm a Stack Overflow moderator" hat and vetoing the idea.

Doing this move so close after the drama is bound to cause exponentially more drama and undue attention.

If you still feel this is needed in a week or two after things have calmed down enough, I'm willing to put it to a vote again.

**Comment by benjamingr** [comment]
> I disagree with making the room a gallery, so much so as to go as far and putting on my "I'm a Stack Overflow moderator" hat and vetoing the idea.

Just so we're clear - You don't get to do that. You're welcome to enforce SO policy but a gallery room is a chat feature and clearly _not_ against SO policy.

If you feel very strongly about this you could have just said so. I opened this post for discussion - not in order to go against or antagonize anyone.

**Comment by rlemon** [comment]
Closing a _github_ issue heavy-handed around the direction of the room is **way not cool** Madara. :( I'm pretty disappointed you'd take this action on behalf of the entire room.    Very disappointing.

**Comment by luggage66** [comment]
I couldn't vote for making the room gallery before addressing the stream of vulgar (but funny) delete comments between ROs that I think already makes it feel like a closed club.

**Comment by MadaraUchiha** [comment]
I apologize if I came off as too forceful, my intention was that doing this kind of move now would definitely reignite the whole thing from both the expected and unexpected angles. Not to mention that there's a distinct possibility that if we do end up doing that, the moderation team (i.e. not me) is likely to intervene and reverse the decision.

Like I said, I don't intend to go around the room owners' wishes here, but there are things you guys don't see that I am not at liberty of sharing in this medium.

**Comment by benjamingr** [comment]
> I apologize if I came off as too forceful, my intention was that doing this kind of move now would definitely reignite the whole thing from both the expected and unexpected angles.

Thank you for the apology. AFAIK no one gets to veto since that's not our governance.

You get a super-vote when it comes to things that enforce SO policy (which is a good thing!) but an equal-among-many vote when it comes to room choices (as they fall within SO policy). Although if you believe that this is something that will be seen negatively by SO staff I'd rather not pursue it anyway to be fair.

**Comment by benjamingr** [comment]
In case anyone missed it - [here is my response to the meta issue](https://meta.stackoverflow.com/questions/366793/recourse-for-inappropriate-stack-overflow-chat-conversation/366822#366822).

**Comment by ssube** [comment]
I don't think we can deny the moderator/staff veto -- there's nothing we can do to prevent the room from being frozen or closed -- but Github is the side channel to debate, and even if the room *was* closed, this debate and repo should stay open.

**Comment by GNi33** [comment]
Even though this is "off the board" already, I also voted no.

I've been thinking about this a little bit though, and I could seriously see us splitting the room up.

17 will be the official, ontopic JavaScript room. I think we have to acknowledge that we are using a room, named after one of the most popular programming languages at the moment, on one of the most popular programming related websites at the moment. As said, 17 would be limited to all things JS

New people coming in will expect this room to be about JavaScript in a somewhat professional setting. Combined with the new "inclusive" movement of SO, a problem like this was bound to happen and I would not be surprised to see it repeat. Of course these people are not likely to understand that the regulars in this room have chatted with each others for years, personally know each other on some occasions and thus just like to chat, about whatever topic.

This creates a problem I think.

I could see us open up a JavaScript - Offtopic branch. And I could see this having more benefits than just avoiding problems like mentioned above. 
On-Topic questions and discussions would not be drowned out by two simultaneous held discussions about 3d printing and whatever Sterling did on the weekend (a little joke, no judgement here). Trolls on 17 can very easily be removed by simply not being ontopic, and I don't see the mods having problems with us closing down the offtopic branch into gallery if things get too heated.

Seeing what happened a few years ago with the EcmaScript - room though, I'd have to say that it would strictly need to be an Offtopic - Ontopic split, with us pointing people to the correct room if things get mixed up. 

Not sure if it would work out, I'd be happy to give it a shot though.

**Comment by MadaraUchiha** [comment]
A room like that is likely to be shut down by SO, a room that's purely for off-topic doesn't really have a place in the chat scheme of things, at least as far as I know. That would also not stop users from trolling and flagging things spoken in this off-topic room.

**Comment by forresthopkinsa** [comment]
@MadaraUchiha Well, I could see an off-topic room being an appropriate 'overflow' for off-topic discussion in other rooms.

I think that `Comments are not for extended discussion...` would lead me to believe that, in the right conditions, Chat _is_ an acceptable medium for, well, extended discussion, as long as it's not impeding on-topic discussion... which, according to some of the chatter across the many channels currently revolving around this topic, is one of the main problems with the transcript: there were people in the room trying to actually ask for Javascript help, not knowing that the JS room is not actually the right place for that.

I think this is something that would be in the best interest of the SO team; it would serve the exact same function that comments-overflow rooms serve: keeping the original discussion in line, while also relieving peripheral pressure.

Thoughts?

**Comment by MadaraUchiha** [comment]
@forresthopkinsa I have broached the subject to the other mods and staff earlier today, actually. The feedback was... mixed. Some think it's worth a shot, while others say that this kind of thing simply has no place in Stack Overflow, and if you want an off-topic chatroom you're better off forming it elsewhere.

**Comment by GNi33** [comment]
> The feedback was... mixed. Some think it's worth a shot, while others say that this kind of thing simply has no place in Stack Overflow, and if you want an off-topic chatroom you're better off forming it elsewhere.

Which is the main culprit in general, right? We want to stay on SO, because we still want to help people, and new members join  through the open and well used platform, which eventually become regulars every now and then, because they enjoy the community.

On the other hand, there's a lot of offtopic talk, because of the community that the chat has become.

We should find a way to see the benefits of both sides here and find a working middle ground. I still think a split might work, even if it would leave the JS chat a little dead for most of the time. Otherwise we would probably need to look for a little stricter rules about the contents discussed in chat. But I'm not sure where to draw a good line there

**Comment by Cerbrus** [comment]
I must say I’m not very keen on having yet another browser tab / application open.

I’ve got too much running as it is already.

**Comment by tentonaxe** [comment]
If the off topic conversations were moved over to a new off topic discussion room we would no longer actually be watching the js chat for new messages as much as we do now. I would expect that to reduce the number of js questions that actually get answered in that room, and in the end I don't think it really resolves the root of the issue. The problem we have isn't related to javascript questions being missed/ignored over off-topic chat/banter, it's the topic of the off-topic chat/banter and how we respond to someone disputing whether or not said off-topic chat is appropriate.

We've had users in the past complain about the fact that we discuss gaming in js chat and typically easily resolved it by pointing them to the github rules page. If they continued and caused a problem, we issue a kick and moved along (this isn't very common.) In this case that didn't work, mostly due to the topic being more controversial than KSP.

I am not in favor of using another platform (or room) and moving js chat to strictly js. I think a middle ground can be reached, more so if the tools we have to deal with problems are improved.

**Comment by forresthopkinsa** [comment]
If SO Chat were updated a bit to include 'Channels' like other more modern chat platforms, then I don't feel like this would be a problem

**Comment by benjamingr** [comment]
By the way - I changed my vote from 👍 to 👎 after members have raised concerns regarding it and since the situation de-escalated so far.

**Comment by 7fe** [comment]
I'm assuming the majority of people that has voted has, but I don't think a majority makes sense when the vote is a close as it is.  Maybe 2/3 or 3/5 vote but a simple majority could be altered by one additional vote at the last minute.

**Comment by kendfrey** [comment]
@limeblack 2/3 majority or 3/5 majority is no different. Any threshold voting can be swayed by a single vote.

Still, I have wondered if 2/3 majority would be a more appropriate standard for our voting...

**Comment by RUJodan** [comment]
I have also changed my vote to 👎due to the de-escalation. I was worried about people coming in to harass us, but if anything, it seems to have brought new people to our doorstep with no motive.

**Comment by Canop** [comment]
I vote against closing the room. Its life comes from new Javascript coders coming from SO and looking from fellow coders.

But renaming the room as ECMAScript might help filter out the too weak-willed ones. Which would be consistent with what *I* look for in this room: a community of coders mostly interested in technical discussion.

I also think trying to bring the room more in focus would also help give more sense to its rules and fight trolling.

**Comment by Zirak** [comment]
No. Unless I missed something, the twitter people stayed on twitter, and nothing serious further happened (inside the room).

We don't let a fly-by user close our room.

**Comment by benjamingr** [comment]
It looks like there are plenty of downvotes now and more than upvotes so I think this is safe to close.

For the record - the process was majority vote and 72 hours which we decided on at some point but I don't feel too strongly about.

Thanks for participating everyone!

**Comment by ndugger** [comment]
I missed this discussion; It's been 2 weeks since this issue has been closed. Has anyone's opinions changed on the matter? I hear some folks moved to discord, but not everyone, or at least not everyone got the invite.

I voted yes on the issue above, for the record.

**Comment by MadaraUchiha** [comment]
I still vote no. I don't feel this is necessary or a good move.

**Comment by ndugger** [comment]
That's fair; do we expect the turmoil to die down, or do you think SO is going to continue to go in the direction of favouring sensitivity over quality?

**Comment by tentonaxe** [comment]
Depends on whether or not they decide to improve the flagging situation. I don't think js chat will return to what it was before, and as such a lot of the more active users likely also won't be as active here anymore.

**Comment by rlemon** [comment]
It won't die down, because SO is pushing it to continue. They encourage the use of the flag system for any slight, and then don't follow up or seem to care when it's used incorrectly.   

Until SO changes this (which I don't think will happen under the current 'management') the chat will probably always attract SJWs looking to 'make SO welcoming again'.

**Comment by benjamingr** [comment]
I still vote no.
