### ISSUE TITLE
RO Voting. 

### ISSUE THREAD

**Issue by rlemon** [JavaScriptRoom/culture#8]
It has been discussed to only allow votes from other RO's count. I disagree with this for two (main) reasons:  
1) we are biased.  
2) room culture is driven by more than just the RO's. "the public" should have a say who is and who is not an RO.  

Now, there should of course be considerations, like; 
have you been part of the room for more than today (or X time) ??  
are you a bot ??  
?? <insert more considerations here>  

Please discuss.

**Comment by kendfrey** [comment]
It will be much easier to allow only ROs, I vote against. Of course, *opinions* can be shared by anyone, and can affect the voting.

**Comment by benjamingr** [comment]
I think everyone who's been in the room long enough and whose opinion we trust becomes an RO anyway if they're interested in room culture and policy. So I think only ROs should vote.

I'm fine with _specific exceptions_ of people who are disinterested in being RO but otherwise meet the qualifications. 

I wouldn't want zigi, noob1992, hitler dude, porizm or any of the trolls we've had over the years to get a vote.

**Comment by GNi33** [comment]
I disagree, because as you said, deciding who gets to vote outside of the RO group will be hard and will lead to even more discussion.

As @kendfrey said, when votings are open, users in the chat can voice their opinion. ROs should be a respected group that sort of represents the demographic of the whole room, so voting should be restrained to this group.

**Comment by rlemon** [comment]
I agree, exceptions should be made.. but I also think users like GNi33 or towc should have a vote. They are in the room quite often and do help quite a few users while here (read: keep the room moving forward on point).

**Comment by loktar00** [comment]
I agree with @GNi33 once exceptions are made it ends up being a pretty slippery slope with feelings being hurt.

**Comment by ssube** [comment]
I think everyone should be allowed to speak, but only ROs should have a vote (one of them representative democracy thingy). 

To keep things fair, maybe poll regulars for their opinions a few days ahead of the vote, so we can get some feedback and think about it?

**Comment by Jhawins** [comment]
http://feathub.com is free and has voting features as well as tallies. Would be a lot more useable than commenting +1/-1, but then we'd be on a different site.

**Comment by rlemon** [comment]
GH is easy to 1:1 accounts to SO.. I know who is who. We can easily setup another site to do voting on with GH or stack auth..

**Comment by Jhawins** [comment]
It uses GH accounts

**Comment by rlemon** [comment]
@Jhawins nice. I honestly didn't look. :D

**Comment by benjamingr** [comment]
@Jhawins was that a comment to @kendfrey's issue?

**Comment by Jhawins** [comment]
We need a time limit for voting

**Comment by benjamingr** [comment]
It doesn't look like this is going to happen unless we have a more concrete proposal.

**Comment by Shmiddty** [comment]
Voting should be based on "citizenship". Citizenship is not mandatory for entry. Acquiring citizenship involves:

1) Being relatively active. (*N* messages over a period of *T*)
2) Naturalization test?
3) Q:A threshold?

Citizenship would be granted automatically upon fulfillment of requirements, and could be used to drive a plethora of functionality.

**Comment by benjamingr** [comment]
@Shmiddty if you have a concrete proposal can you please open an issue so we can vote on it?
