### ISSUE TITLE
A *meta* room for room-related discussions

### ISSUE THREAD

**Issue by erikroyall** [JavaScriptRoom/culture#9]
I propose this, considering room-related discussions are OT and are better discussed elsewhere. Just my  0.0001 BTC.

**Comment by benjamingr** [comment]
We tried this, some other room owners feel very strongly against this (ping @rlemon ). While I'm in favor of a separate room I'm not interested in causing these people discomfort over it.

**Comment by erikroyall** [comment]
> in causing these people discomfort over it
I understand. But room 7 doesn't seem to be the place for these discussions. People who are new to the room find this.. well..

http://chat.stackoverflow.com/transcript/message/28230332#28230332
http://chat.stackoverflow.com/transcript/message/28230372#28230372

**Comment by rlemon** [comment]
@erikroyall  I am against this. If prolonged discussion needs to happen we can one-off that, but room discussions should be visible and public to all in the room. Recently I can understand how this has been sort of annoying because there has been an over abundance of issues, but normally I would hope this isn't the case.   

Re: the two links you posted,  
it looks like the first was just asking if we accepted questions, this is nothing new.. The second looks like someone complaining about being OT. OT discussing the room is different than OT discussing our next car purchase how??

**Comment by darkyen** [comment]
:-1:

**Comment by benjamingr** [comment]
I'll keep it open for 24 hours and will then close unless anyone objects.

**Comment by erikroyall** [comment]
This repository has been doing really well. Kudos to those who've come up with this idea. No need of a *meta* room anymore.
